// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopEsameElis.Models
{
    public partial class Cart
    {
        public int IdCart { get; set; }
        public int? IdUtente { get; set; }
        public int? IdProduct { get; set; }
        public virtual Product IdProductNavigation { get; set; }
        public virtual Utente IdUtenteNavigation { get; set; }

        
    }
}