// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopEsameElis.Models
{
    public partial class Product
    {
        public Product()
        {
            Carts = new HashSet<Cart>();
        }

        public int IdProduct { get; set; }
        public string Name { get; set; }
        public decimal? Price { get; set; }
        public short? Quantity { get; set; }
        public int? IdShop { get; set; }

        public virtual Shop IdShopNavigation { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }

        public void modifyQuantity(int quantity)
        {
            try
            {
                if (this.Quantity >= quantity)
                {
                    Quantity = (short?)(int)(Quantity - quantity);
                }
            }catch (Exception ex)
            {
                HttpClient.ReferenceEquals(this, ex);
            }
        }
    }
}