// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ShopEsameElis.Models
{
    public partial class ShopContext : DbContext
    {
        public ShopContext()
        {
        }

        public ShopContext(DbContextOptions<ShopContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Utente> Utentes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cart>(entity =>
            {
                entity.HasKey(e => e.IdCart)
                    .HasName("PK__Cart__8BA3E887CE9AA9B0");

                entity.ToTable("Cart");

                entity.Property(e => e.IdCart).HasColumnName("idCart");

                entity.Property(e => e.IdProduct).HasColumnName("idProduct");

                entity.Property(e => e.IdUtente).HasColumnName("idUtente");

                entity.HasOne(d => d.IdProductNavigation)
                    .WithMany(p => p.Carts)
                    .HasForeignKey(d => d.IdProduct)
                    .HasConstraintName("FK__Cart__idProduct__3F466844");

                entity.HasOne(d => d.IdUtenteNavigation)
                    .WithMany(p => p.Carts)
                    .HasForeignKey(d => d.IdUtente)
                    .HasConstraintName("FK__Cart__idUtente__403A8C7D");
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.IdProduct)
                    .HasName("PK__Product__5EEC79D1B57A39E4");

                entity.ToTable("Product");

                entity.Property(e => e.IdProduct).HasColumnName("idProduct");

                entity.Property(e => e.IdShop).HasColumnName("idShop");

                entity.Property(e => e.Name)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("name");

                entity.Property(e => e.Price)
                    .HasColumnType("money")
                    .HasColumnName("price");

                entity.Property(e => e.Quantity).HasColumnName("quantity");

                entity.HasOne(d => d.IdShopNavigation)
                    .WithMany(p => p.Products)
                    .HasForeignKey(d => d.IdShop)
                    .HasConstraintName("FK__Product__idShop__3C69FB99");
            });

            modelBuilder.Entity<Shop>(entity =>
            {
                entity.HasKey(e => e.IdShop)
                    .HasName("PK__Shop__C4D7768FEB64661C");

                entity.ToTable("Shop");

                entity.Property(e => e.IdShop).HasColumnName("idShop");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<Utente>(entity =>
            {
                entity.HasKey(e => e.IdUtente)
                    .HasName("PK__Utente__11EA834F590AD25B");

                entity.ToTable("Utente");

                entity.Property(e => e.IdUtente).HasColumnName("idUtente");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("name");

                entity.Property(e => e.Surname)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("surname");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}